// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SGE-AI/sge-bot/config"
	"github.com/SGE-AI/sge-bot/gpt"
	"github.com/SGE-AI/sge-bot/interfaces"
	"github.com/SGE-AI/sge-bot/logger"
	"github.com/SGE-AI/sge-bot/repository"
	"github.com/SGE-AI/sge-bot/slackapi"
	"github.com/SGE-AI/sge-bot/usecase"
)

// Injectors from wire.go:

func initializeApp() *Application {
	configConfig := config.ProvideConfig()
	loggerLogger := logger.ProvideLogger()
	client := gpt.ProvideGPTClient(configConfig, loggerLogger)
	slackAPI := slackapi.ProvideSlackAPI(configConfig, loggerLogger)
	contextCancelRepository := repository.ProvideContextCancelRepository()
	chat := usecase.ProvideChat(client, configConfig, loggerLogger, slackAPI, contextCancelRepository)
	spreadsheetRepository := repository.ProvideSpreadsheetRepository(configConfig, loggerLogger)
	statistics := usecase.ProvideStatistics(spreadsheetRepository, loggerLogger)
	eventHandler := interfaces.ProvideEventHandler(configConfig, loggerLogger, chat, statistics)
	socketConnection := interfaces.ProvideSocketConnection(configConfig, eventHandler, loggerLogger)
	application := ProvideApplication(configConfig, loggerLogger, socketConnection, slackAPI)
	return application
}
